development:
  adapter: postgresql
  database: softkoi_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: softkoi_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: softkoi_production
  pool: 5
  timeout: 5000
